### ISSUE TITLE
A PHP warning is generated by the daily Cron

### ISSUE THREAD

**Issue by ronalfy** [strangerstudios/pmpro-pay-by-check#53] opened 2020-05-18 12:57 UTC
A PHP warning is generated by the daily Cron on line 685 of this add on.

The error is coming through by the daily Cron process: `pmpropbc_recurring_orders`

Here is the PHP notice received.

```bash
PHP Warning: Creating default object from empty value in /home/local/public_html/wdpr/wp-content/plugins/pmpro-pay-by-check/pmpro-pay-by-check.php on line 685
```

**Comment by okozarsky** [comment] 2020-06-21 19:21
I hope that when the issue is resolved you will push an update eto the Plugin. Thanks

**Comment by okozarsky** [comment] 2020-07-23 14:06
any update on this issue? The plugin is still throwing error logs

**Comment by andrewlimaza** [comment] 2022-09-05 11:43
I haven't been able to replicate this as of today, I tried to run the recurring_orders code manually and trigger this, I am going to close this issue. If you still are experiencing this issue @okozarsky please let us know by creating an issue and letting us know how to replicate it based off your level settings.

**Closed by andrewlimaza** 2022-09-05 11:43 UTC
Labels: Difficulty: Medium
